### ISSUE TITLE
No UI in snippets view

### ISSUE THREAD

**Issue by Yzrsah** [usernamehw/vscode-snippets-view#1]
On VSCode 1.32-insiders:

The snippets view is empty, it has nothing there, no UI

**Comment by usernamehw** [comment]
* Was it working before?
* Is there any errors in the console? `Developer: Toggle Developer Tools`
* OS?
* Are you using different user data dir? `--user-data-dir`

**Comment by usernamehw** [comment]
You can file issues against extensions with Issue Reporter. It will fill extension version, OS, OS version for you:
![screenshot 51](https://user-images.githubusercontent.com/9638156/52416687-36705480-2afb-11e9-97f2-d783acddddf5.png)

**Comment by Yzrsah** [comment]
I was able to resolve the issue. The extension is good, thank you.

Do you plan to support viewing snippets provided by extensions? It would be very helpful to view extension-provided snippets, because they can get large/disorganized or inconsistent, and viewing them would help to get a grasp of the whole setup.

**Comment by usernamehw** [comment]
Closing this then. Created a separate issue for extension snippets #2.
