### ISSUE TITLE
Include extension contributed snippets

### ISSUE THREAD

**Issue by usernamehw** [usernamehw/vscode-snippets-view#2]
- [x] Setting to disable fetching of extension snippets
- [x] Should they be in a separate View?
> They are currently all in the same View, but have different icons (folder) (that doesn't work if the icons disabled though...)
- [ ] A lot of activation/deactivation events out there. Need to fetch all snippets **OR**
have a listener(s) to access snippets from enabled extensions **OR** 
at least have a way to exclude files from the View
 > No plans to have a ton of event listeners or hacks
- [x] Should `Open Snippets File` be disabled for extension snippets? Modifying the document doesn't make sense since the changes will be overwritten on vscode/extension update
  > Nah, it's a useful feature. I'll just assume the users are smart not to modify extension snippets.
- [x] Need `Collapse All` button bc the View gets crowded real quick
- [x] Should Empty folder be excluded from the View?
 > No, it's still useful to go to Snippet File
- [x] Should folder(file) containing only `Region Start` & `Region End` be excluded from the View?
 > Yes

**Comment by Yzrsah** [comment]
Thank you. Viewing extension snippets will be extremely helpful

**Comment by Yzrsah** [comment]
Thank you. Viewing extension snippets will be very helpful

**Comment by usernamehw** [comment]
It will probably take a lot longer to write something good. In `0.2.0` you can enable first version of it with 
```json
"snippets-view.includeExtensionSnippets": true,
```
